ENCODING_UTF8 	= 65001
ENCODING_LATIN 	= 1252

MOBI_TYPE_BOOK 	= 2
MOBI_TYPE_NEWS 	= 257
MOBI_TYPE_TXT 	= 517
MOBI_TYPE_HTML 	= 518
	
LOCALE_ENGLISH 		= 9
LOCALE_ENGLISH_UK 	= 2057
LOCALE_ENGLISH_US	= 1033
	
EXTH_RECORD_TYPE_AUTHOR 				= 100
EXTH_RECORD_TYPE_PUBLISHER 				= 101
EXTH_RECORD_TYPE_IMPRINT 				= 102
EXTH_RECORD_TYPE_DESCRIPTION 			= 103
EXTH_RECORD_TYPE_ISBN 					= 104
EXTH_RECORD_TYPE_SUBJECT 				= 105
EXTH_RECORD_TYPE_PUBLISHING_DATE 		= 106
EXTH_RECORD_TYPE_REVIEW 				= 107
EXTH_RECORD_TYPE_CONTRIBUTOR 			= 108
EXTH_RECORD_TYPE_RIGHTS 				= 109
EXTH_RECORD_TYPE_SUBJECTCODE 			= 110
EXTH_RECORD_TYPE_TYPE 					= 111
EXTH_RECORD_TYPE_SOURCE 				= 112
EXTH_RECORD_TYPE_ASIN 					= 113
EXTH_RECORD_TYPE_VERSION 				= 114
EXTH_RECORD_TYPE_RETAIL_PRICE 			= 118
EXTH_RECORD_TYPE_RETAIL_CURRENCY 		= 119
EXTH_RECORD_TYPE_COVER_OFFSET 			= 201
EXTH_RECORD_TYPE_THUMB_OFFSET 			= 202
EXTH_RECORD_TYPE_CREATOR_SOFTWARE 		= 204
EXTH_RECORD_TYPE_CREATOR_VERSION_MAJOR 	= 205
EXTH_RECORD_TYPE_CREATOR_VERSION_MINOR 	= 206
EXTH_RECORD_TYPE_CREATOR_VERSION_BUILD 	= 207
EXTH_RECORD_TYPE_LANGUAGE 				= 524

EXTH_CREATOR_MOBIGEN 			= 1
EXTH_CREATOR_MOBIPOCKET			= 2
EXTH_CREATOR_KINDLEGEN_WINDOWS 	= 200
EXTH_CREATOR_KINDLEGEN_LINUX 	= 201
EXTH_CREATOR_KINDLEGEN_MAC 		= 202

TRAILING_MULTIBYTE 			= 0x001
TRAILING_INDEXING 			= 0x002
TRAILING_UNCROSSABLE_BREAK 	= 0x004

RECORD_SIZE = 4096